name: GitHub Classroom Workflow

on: [push]

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
    # lint:
    # runs-on: ubuntu-20.04
    #steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: Run linter
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        run: yarn --frozen-lockfile
      - name: Run syntax rules check with ESLint
        run: yarn lint
      - uses: actions/checkout@v2
      - uses: education/autograding@v1

  
