name: GitHub Classroom Workflow

on: [push]

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: education/autograding@v1
    lint:
    # runs-on: ubuntu-20.04
    #steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: Run linter
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        run: yarn --frozen-lockfile
      - name: Run syntax rules check with ESLint
        run: yarn lint
  build-with-canvas:
    env:
      TEST_SUITE: 'node-canvas'
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: Run Canvas tests with Node 18
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install required image manipulation packages with APT
        run: sudo apt-get install build-essential libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev
      - name: Setup HOSTS file for Web Platform Test server
        run: ./test/web-platform-tests/tests/wpt make-hosts-file | sudo tee -a /etc/hosts
      - name: Install dependencies
        run: yarn --frozen-lockfile
      - name: Run tests
        run: yarn add canvas && yarn test --retries 1
  build-with-browser:
    env:
      TEST_SUITE: 'browser'
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: Run web browser tests
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Setup HOSTS file for Web Platform Test server
        run: ./test/web-platform-tests/tests/wpt make-hosts-file | sudo tee -a /etc/hosts
      - name: Install dependencies
        run: yarn --frozen-lockfile
      - name: Run tests
        run: yarn test-browser
  # build:
   # runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        node-version:
          - 14
          - 16
          - 18
        architecture:
          - x64
  
