name: HTML5 Validator
run-name: HTML5 Validator
on: [push]
jobs:
  build:
    name: Validator
    runs-on: ubuntu-latest
    steps:
    - name: HTML5 Validator
    - uses: Cyb3r-Jak3/html5validator-action@v7.2.0
    - name: HTML5Validator
    - uses: Cyb3r-Jak3/html5validator-action
      with:
        root: tests/
        blacklist: invalid
